# Generated by Django 3.0.2 on 2020-01-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200129_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events-pics')),
                ('title', models.CharField(max_length=200)),
                ('quiz', models.CharField(max_length=500)),
                ('content', models.TextField()),
            ],
        ),
    ]
