# Generated by Django 3.0.2 on 2020-01-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='videofile',
        ),
        migrations.AddField(
            model_name='video',
            name='videourl',
            field=models.CharField(default='', max_length=2083),
            preserve_default=False,
        ),
    ]
