# Generated by Django 3.0.2 on 2020-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_auto_20200129_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default='', upload_to='picha'),
            preserve_default=False,
        ),
    ]
