# Generated by Django 3.0.2 on 2020-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_video_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
