# Generated by Django 3.0.2 on 2020-01-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
